twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        prod_url: 'https://pansion-babic.hr/'

when@test:
    twig:
        strict_variables: true
