controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

redirect:
    path: /
    controller: App\Controller\HomeController::indexAction
    defaults:
        path: '/%locale%'
        permanent: false
